In [1]:
import numpy as np

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b=[arr%2==1]
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b

[array([False,  True, False,  True, False,  True, False,  True, False,
         True])]

In [5]:
arr[b]

C:\Users\Dell\OneDrive\Documents\envs\py36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([1, 3, 5, 7, 9])

In [6]:
arr[b]=-1
arr

C:\Users\Dell\OneDrive\Documents\envs\py36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [12]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [18]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [19]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [20]:
a = np.array([1,2,3])

In [21]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [23]:
np.intersect1d(a,b)

array([2, 4])

In [24]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [25]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [26]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [27]:
b=np.where((a>=5)&(a<=10))
a[b]

array([ 6,  9, 10])

In [28]:
a[(a>=5)&(a<=10)]

array([ 6,  9, 10])

In [29]:
b = np.where(np.logical_and(a>=5, a<=10))
a[b]

array([ 6,  9, 10])

In [30]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [34]:
arr[:,[2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [33]:
arr[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [35]:
ra_arr=np.random.uniform(5,10,size=(5,3))
print(ra_arr)

[[7.14867755 9.83274552 8.22769932]
 [7.26032247 9.61558395 8.86302824]
 [6.2599221  8.29169655 8.5612641 ]
 [6.12035874 6.07713737 6.7294049 ]
 [8.30285338 5.42672746 6.87744502]]


In [38]:
rand_arr=np.random.random([5,3])
print(rand_arr)

[[0.529931   0.34620009 0.93085454]
 [0.96959685 0.59334228 0.91398568]
 [0.08507522 0.70137574 0.69491012]
 [0.87248863 0.2924418  0.4561303 ]
 [0.01854774 0.72188209 0.29907983]]


In [39]:
np.set_printoptions(precision=3)
print(rand_arr)

[[0.53  0.346 0.931]
 [0.97  0.593 0.914]
 [0.085 0.701 0.695]
 [0.872 0.292 0.456]
 [0.019 0.722 0.299]]
